---

- name: genera Jenkinsfile
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "./Jenkinsfile-{{ item.name }}"
  loop: "{{ pipelines | selectattr('template', 'equalto', 'main-template.j2') | list }}"


- name: genera Jenkinsfile per pull e pull-push
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "./Jenkinsfile-{{ item.name }}"
  loop: "{{ pipelines | selectattr('template', 'equalto', 'push-pull.j2') | list }}"