---

pipelines:
  - name: node-exporter
    template: main-template.j2
    agent: any
    abilita_recovery: true
    abilita_metriche: true
    abilita_email: true
    max_restart: 3
    service_name: node_exporter
    check_url: "http://192.168.3.165:9100/metrics"
    restart_url: "http://192.168.3.165:5000/restart"
    metrics_url: "http://192.168.3.165:9100/metrics"
    metriche:
      - env_var: HOSTNAME
        etichetta: hostname
        estrazione: "grep '^node_uname_info' | grep -oP 'nodename=\"\\K[^\"]+'"
      - env_var: KERNEL
        etichetta: kernel
        estrazione: "grep '^node_uname_info' | grep -oP 'release=\"\\K[^\"]+'"
      - env_var: LOAD_AVERAGE
        etichetta: load_average
        estrazione: "awk '/^node_load1 / {print \\$2}'"
      - env_var: AVAILABLE_RAM
        etichetta: available_ram
        estrazione: "awk '/^node_memory_MemAvailable_bytes / {print \\$2 / 1024 / 1024 / 1024}'"
    email_to: "jenny.bellucci@sourcesense.com"
    email_subject: "metriche"

  - name: cluster-rabbitmq
    template: main-template.j2
    agent: any
    abilita_parametri: true
    abilita_download: true
    abilita_deploy_rabbitmq: true
    abilita_aspetta_pod: true
    abilita_vhost: true
    abilita_user: true
    credential: kubeconfig-cluster-rabbitmq
    namespace: cluster-rabbitmq
    cluster: trove-rabbitmq-test
    name_download: kubectl
    download:
      - url_download: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        permissions: kubectl
    name_deploy: rabbitmq
    manifest: rabbitmq-trove-cluster-local.yaml
    strumento: ./kubectl
    users:
      - name: user1
        name_params: ROMA
        vhost: roma
        user: roma
        id: trove-roma
      - name: user2
        name_params: MILANO
        vhost: milano
        user: milano
        id: trove-milano

  - name: recovery
    template: main-template.j2
    agent: any
    abilita_recovery: true
    max_restart: 6
    service_name: node_exporter
    check_url: "http://192.168.3.165:9100/metrics"
    restart_url: "http://192.168.3.165:5000/restart"
    metrics_url: "http://192.168.3.165:9100/metrics"
    metriche:
      - env_var: HOSTNAME
        etichetta: hostname
        estrazione: "grep '^node_uname_info' | grep -oP 'nodename=\"\\K[^\"]+'"
      - env_var: KERNEL
        etichetta: kernel
        estrazione: "grep '^node_uname_info' | grep -oP 'release=\"\\K[^\"]+'"
      - env_var: LOAD_AVERAGE
        etichetta: load_average
        estrazione: "awk '/^node_load1 / {print \\$2}'"
      - env_var: AVAILABLE_RAM
        etichetta: available_ram
        estrazione: "awk '/^node_memory_MemAvailable_bytes / {print \\$2 / 1024 / 1024 / 1024}'"
    email_to: "jenny.bellucci@sourcesense.com"
    email_subject: "metriche"

  - name: install
    template: main-template.j2
    agent: any
    abilita_download: true
    name_download: kubectl
    download:
      - url_download: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        permissions: kubectl

  - name: pull-push
    template: push-pull.j2
    agent: any
    images:
      nginx:
        name_image: nginx
        source:
          repo: "staging.local:5000"
          tag: "1.27-rc3"
        targets:
          - repo: "prod.local:5000"
            tag: "1.27"
          - repo: "prod.local:5000"
            tag: "stable"
          - repo: "dr.local:5000"
            tag: "1.27"
      redis:
        name_image: redis
        source:
          repo: "staging.local:5000"
          tag: "7.4"
        targets:
          - repo: "prod.local:5000"
            tag: "7.4"

  - name: pull-push2
    template: push-pull.j2
    agent: any
    images:
      nginx:
        source:
          repo: "staging.local:5000"
          tag: "1.27-rc3"
        targets:
          - repo: "prod.local:5000"
            tag: "1.27"
      redis:
        source:
          repo: "staging.dislocal:5000"
          tag: "7.4"
        targets:
          - repo: "provincia.local:5000"
            tag: "7.4"
